swagger: "2.0"
info:
  description: |
    # Introduction
    This API document outlines how you can access different Nuance services using our concise, yet flexible HTTP API.
    This API provides access to the following services:
      - Speech Recognition
      - Dialog
      - Speech Recognition & Dialog
      - NLU
      - Speech Recognition & NLU
      - Text to Speech (TTS)
      - Vocal Password
    # API Basics
      - All requests must include the `Content-Type: application/json`
    # Authentication
    You must include the following header in every request to authenticate:
      - `nmaid: <your nmaid>`
      - `nmaidkey: <your nmaid key>`
  x-logo:
    url: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a8/Nuance_Communications_logo.svg/640px-Nuance_Communications_logo.svg.png"
  version: "1.0.0"
  title: Nuance HTTP API
  termsOfService: http://nuancecommunications.com
  contact:
    email: hasan.ahmed@nuance.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: <ip>
basePath: /nina-webapi/
schemes:
  - https
tags:
  - name: Speech Recognition
    description: Speech Recognition Functions
  - name: TTS
    description: Text To Speech Functions
  - name: NLU
    description: Natural Language Understading Functions
paths:
  /DoSpeechRecognition:
    post:
      tags:
        - Speech Recognition
      summary: Speech Recognition
      description: "Does speech recognition operations on an audio file using the MREC , NTE or NR engines."
      operationId: speechRecognition
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: "`sr_audio_file` on which the speech recognition is to be done"
          required: true
          schema:
            $ref: "#/definitions/Speech_Reco_Payload"
      responses:
        "200":
          description: Successful operation.
          schema:
            $ref: "#/definitions/Speech_Reco_Response"
        "400":
          description: Bad request. Invalid or missing parameter.
        "401":
          description: Unauthorized. API key is missing or invalid.
  /TTS:
    post:
      tags:
        - TTS
      summary: Text To Speech
      description: "Does TTS operations on the provided string."
      operationId: TTS
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Speech_Reco_Payload"
      responses:
        "200":
          description: ByteBuffer of raw PCM Data.
        "400":
          description: Bad request. Invalid or missing parameter.
        "401":
          description: Unauthorized. API key is missing or invalid.
  /NLU:
    post:
      tags:
        - NLU
      summary: NLU
      description: "Does NLU operations on a text string and returns the results"
      operationId: NLU
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/nlu_payload"
      responses:
        "200":
          description: Successful operation.
          schema:
            $ref: "#/definitions/nlu_response"
        "400":
          description: Bad request. Invalid or missing parameter.
        "401":
          description: Unauthorized. API key is missing or invalid.
definitions:
  Speech_Reco_Payload:
    type: object
    required:
      - sr_audio_file
    properties:
      sr_audio_file:
        description: Direct URL to the audio file. Must be a WAV, MP4 or AAC file.
        type: string
        example: https://dl.dropboxusercontent.com/s/4ygn9m8wscadl22/TestAudioUpload.wav
      sr_engine:
        description: The sr_engine parameter is optional, the default engine is specified by your licence file (specific to a given NMAID ID).
        type: string
        example: MREC, NR, or NTE
      sr_engine_parameters:
        description: The sr_engine_parameters parameter is an optional json object and only looked at when engine = NTE.
        allOf:
          - $ref: '#/definitions/sr_engine_parameters'
      user:
        description: The user id  for who this request is being executed.
        type: string
        example: "123423"
  sr_engine_parameters:
    type: object
    required:
      - operating_mode
    properties:
      operating_mode:
        description: The operating mode. Must be accurate, fast or warp.
        type: strings
        example: accurate
  Speech_Reco_Response:
    type: object
    required:
      - transcription
    properties:
      transcription:
        description: The transcription results.
        type: string
        example: "Hello"
  playaudio_payload:
    type: object
    required:
      - text
    properties:
      text:
        description: The text for which the TTS service should be performed.
        type: string
        example: Hello!
      tts-type:
        description: This parameter is optional and has a default value of text. Its value must text, ssml or uri.
        type: string
        example: text
      barge-in:
        description: This parameter is optional and has a default value of false.
        type: boolean
        example: true
      sr_engine:
        description: This parameter is optional and is only looked that when barge-in is set to true. Your license file (specific to your NMAID) specifies the default engine. Its value must be MREC, NTE or NR.
        type: string
        exaple: MREC
      sr_engine_parameters:
        description: The sr_engine_parameters parameter is an optional json object and only looked at when engine = NTE.
        allOf:
          - $ref: '#/definitions/sr_engine_parameters'
      user:
        description: The user id  for who this request is being executed.
        type: string
        example: "123423"
  nlu_payload:
    type: object
    required:
      - text
    properties:
      text:
        description: The input text on which to perform NLU.
        type: string
        example: Hello!
      nlu_engine:
        description: This parameter is optional, the default engine is specified by your licence file (specific to your NMAID). Its value must be NR or NLE.
        type: string
        example: NR
      nlu_engine_parameters:
        description: This parameter is an optional json object and only looked at when nlu_engine = NLE.
        allOf:
          - $ref: '#/definitions/nlu_engine_parameters'
      user:
        description: The user id  for who this request is being executed.
        type: string
        example: "123423"
  nlu_engine_parameters:
    type: object
    required:
      - nleModelURL
      - nleModelName
    properties:
      nleModelURL:
        type: string
      nleModelName:
        type: string
  nlu_response:
    type: object
    required:
      - results
    properties:
      results:
        description: The results of the NLU operation.
        type: array
        items:
          $ref: '#/definitions/nlu_result_item'
  nlu_result_item:
    type: object
    required:
      - concepts
      - confidence
      - intent
      - literal
    properties:
      concepts:
        description: The concepts.
        type: array
      confidence:
        description: The confidence level of the NLU result.
        type: integer
        format: int32
        example: 25
      intent:
        description: The intent.
        type: string
        example: SOCIAL_GREETING
      literal:
        description: The literal.
        type: string
        example: hello
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
